# Site settings
title: Code, etc.
header-img: img/home-bg.png
email: micah.shute@gmail.com
copyright_name: micahshute
description: > # this means to ignore newlines until "baseurl:"
  Sharing thoughts, ideas, code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  micahshute
learn_profile: micahshute
email_username: micah.shute@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
